# Generated by Django 4.2.2 on 2024-05-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_deactivate', 'can deactivate post')], 'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
    ]
